### ISSUE TITLE
Implement filtering capabilities for export commmand

### ISSUE THREAD

**Issue by otarza** [wfp/content_sync#11]
While exporting we should be able to filter content.

- [x]  We need to be able to export content of specific content type. 
- [x]  We need to be able export taxonomies of specific vocabulary.

**Comment by ademarco** [comment]
Exporting content of a specific content type was already possible by specifying the option `--bundle`:

```
$ console help content-sync:export:nodes
Usage:
  content-sync:export:nodes [options] [--] <folder> [<conditions_string>]

Arguments:
  folder                  Root folder where to import/export content.
  conditions_string       Argument for storage condition in following format "field_name,value,operator,langcode"

Options:
  -b, --bundle[=BUNDLE]   Export only entities of specified bundle (optional).
```

As for the proposed advanced filtering I would expose it not as an argument but as an option, as we do for bundle:

```
abstract class AbstractExportCommand extends AbstractCommand implements ExportCommandInterface {

  /**
   * {@inheritdoc}
   */
  protected function configure() {
    parent::configure();
    $this->addOption('bundle', 'b', InputOption::VALUE_OPTIONAL, $this->trans('command.content-sync.export.options.bundle'));
  }
```

so we could call it `--filters` or `--conditions`, I would keep only the folder as the only mandatory argument. @otarza what do you think?
