### ISSUE TITLE
Allow importing from multi level folder structure

### ISSUE THREAD

**Issue by otarza** [wfp/content_sync#13]
- [ ]  Improve import content process to allow importing from multi level folder structure.

We should be able to import content from multi level folder structure as export command exports all content under the folder named after entity type.

e.g. When we export menu links in folder called `content`, our module creates folder `content/menu_link_content`.

If we export nodes to  `content` folder `content/node` folder will be created.

After that if we need to import these content we need to execute import command for each of the entity types because they are under different folders.

**Comment by ademarco** [comment]
this is actually already the case, you just need to call `drupal content-sync:import ./content` and it will recurse in the root directory and import all content.
